# 创建账号
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemanagement-admin
  namespace: kubemanagement-system

---

# 创建角色
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubemanagement-role
  namespace: kubemanagement-system

rules:
  - apiGroups:
      - ""
    resources:
      - pod
    verbs:
      - get
      - list

---

# 账号、角色绑定
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubemanagement-admin-crb
  namespace: kubemanagement-system

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubemanagement-role
subjects:
  - kind: ServiceAccount
    name: kubemanagement-admin
    namespace: kubemanagement-system