version: "3"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

services:
  web:
    container_name: kubemanagement-web
    image: harbor.kubemanagement.com/kubemanagement/kubemanagement-web:v1.0
    restart: always
    environment:
      BACKEND_HOST: 'http://177.7.0.12:8082/'
    ports:
      - '8081:80'
    depends_on:
      - server
    networks:
      network:
        ipv4_address: 177.7.0.11

  server:
    container_name: kubemanagement-server
    image: harbor.kubemanagement.com/kubemanagement/kubemanagement:v1.0
    restart: always
    ports:
      - '8082:8082'
    networks:
      network:
        ipv4_address: 177.7.0.12