version: "3"

volumes:
  dronedata:

services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    environment:
      DRONE_AGENTS_ENABLED: "true"
      DRONE_GOGS_SERVER: "http://192.168.65.134:10880"
      # openssl rand -hex 16 生成， server 与 runner 的 DRONE_RPC_SECRET 设置相同
      DRONE_RPC_SECRET: "02cfbfe91f999c6f334158f4cf737490"
      DRONE_SERVER_HOST: "192.168.65.134:9080"
      DRONE_SERVER_PROTO: "http"
      # 必须是管理员身份，方便后续的配置选项等操作
      DRONE_USER_CREATE: "username:BetaCatPro,admin:true"
    volumes:
    - dronedata:/data
    restart: always
    ports:
    - '9080:80'
    - '9443:443'
  
  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    environment:
      DRONE_RPC_SECRET: "02cfbfe91f999c6f334158f4cf737490"
      DRONE_RPC_HOST: "192.168.65.134:9080"
      DRONE_RPC_PROTO: "http"
      DRONE_RUNNER_CAPACITY: "2"
      DRONE_RUNNER_NAME: "first-runner"
    volumes:
    - /etc/docker/:/etc/docker
    - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
    - '3000:3000'
    depends_on:
    - drone-server
