# 一次性任务
kind: Job
apiVersion: batch/v1
metadata:
  name: hello
  namespace: test
spec:
  # 仅支持 onFailure , never
  restartPolicy: never
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
          - /bin/sh
          - -c
          - echo "Hello"